export const TxType = {
  TxTypeEmpty: 0,
  TxTypeRegisterZns: 1,
  TxTypeCreatePair: 2,
  TxTypeUpdatePairRate: 3,
  TxTypeDeposit: 4,
  TxTypeDepositNft: 5,
  TxTypeTransfer: 6,
  TxTypeSwap: 7,
  TxTypeAddLiquidity: 8,
  TxTypeRemoveLiquidity: 9,
  TxTypeWithdraw: 10,
  TxTypeCreateCollection: 11,
  TxTypeMintNft: 12,
  TxTypeTransferNft: 13,
  TxTypeAtomicMatch: 14,
  TxTypeCancelOffer: 15,
  TxTypeWithdrawNft: 16,
  TxTypeFullExit: 17,
  TxTypeFullExitNft: 18,
  TxTypeOffer: 19,
} as const;
